name: Sync Character Markdown

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily sync

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v3

      - name: Clone character repo
        run: |
          git clone https://github.com/hsmalley/velvet-chains temp-characters

      - name: Copy Markdown files
        run: |
          mkdir -p src/content/characters
          cp temp-characters/characters/md/*.md src/content/characters/

      - name: Commit updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/content/characters/*.md
          git commit -m "Sync character sheets from Velvet Chains repo"
          git push
        continue-on-error: true
